### ISSUE TITLE
No API to configure the user agent on iOS

### ISSUE THREAD

**Issue by olivierkorner** [readium/readium-lcp-client#46]
The API is missing some kind of configuration for the application user agent.
On iOS, the user agent sent with each request by the LCP module is the one URLSession instantiated by the iOSNetProvider. There is no way to change to user agent once the URLSession has been created, hence the LCP module should allow a configuration value to be passed to initialize the user agent of the session.

**Comment by llemeurfr** [comment]
And this is a real issue, as we ask app developers to customize their user agent, so that servers may check the promise of a good LCP support of the app.

**Comment by olivierkorner** [comment]
Indeed the LSD implementation instantiates its own NSURLSession, so it's pretty straightforward to set the user agent for these interactions once you fork it.
But I was referring to the download of encrypted EPUBs, which is when the servers actually need to know the user agent. But maybe I'm mistaken and it's not important at this stage... @llemeurfr ?

**Comment by llemeurfr** [comment]
Well, in practice customizing the user agent is the only pragmatic way we found to allow a bookseller/library server to detect if the calling app is supporting LCP or not. But it's true that such detection can only occur before the LCP processus is active: it is useful if the app fetches a page on the buy/loan portal where a download link is available, or fetches an OPDS feed (which could then provide a feed of LCP licenses). These two use-cases are out of scope of what we can test when we validate LCP compliance, therefore modifying the ObjectiveC LCP module now appears unneeded to me.
