### ISSUE TITLE
LCP client samples

### ISSUE THREAD

**Issue by sturegan** [readium/readium-lcp-client#52]
Hi, I've been working on a .NET implementation of LCP client and can't get the sample lcpl files to work correctly and would like some help. Would it be possibe to start an email conversation with Daniel to discuss please?

**Comment by danielweck** [comment]
Did you download the sample LCP licenses from this URL?
https://www.edrlab.org/readium-lcp/testing-readium-lcp-compliant-devices/

If so, these are LCP 1.0 compliant publications (protected with the "production" profile of LCP). You will not be able to process these files with the open-source `readium-lcp-client` codebase alone.

That being said, you can run tests based on publications protected with the non-production profile of LCP, called "basic". The provider certificate is available in the open-source codebase:

https://github.com/readium/SDKLauncher-Android/blob/feature/lcp/SDKLauncher-Android/app/src/main/assets/lcp/lcp.crt

or:

https://github.com/readium/SDKLauncher-iOS/blob/feature/lcp/Resources/LCP%20Root%20Certificate.crt

Here is a working sample EPUB (LCP passphrase is "dan"):

https://github.com/readium/r2-testapp-js/blob/develop/misc/epubs/wasteland-otf-obf_LCP_dan.epub

Note that the LCP license references a now-defunct server URL https://rcs-test.edrlab.org
However this should not impact your rudimentary LCP decryption tests (only the LSD functionality will be affected).

If you are interested in implemented full 1.0 support for LCP (including LSD), please contact @llemeurfr 

Thanks!

**Comment by sturegan** [comment]
Thanks Daniel. I did download the samples from that first link. Will now have a look at the other links you mention.

**Comment by sturegan** [comment]
That worked fine. Thanks for your help.
